jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "11"
        - "stable"
    - stage: release
      language: node_js
      node_js:
        - "11"
        - "stable"
      before_deploy: yarn build
      deploy:
        provider: releases
          api_key: "$GH_TOKEN"
          file_glob: true
          file: dist/*
          skip_cleanup: true